# Copyright (C) 2025 ChenPi11.
# This file is part of chenpi11-blog.
#
# chenpi11-blog is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# chenpi11-blog is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with chenpi11-blog.  If not, see <https://www.gnu.org/licenses/>.

[tasks.autogen]
description = "Generate configure script."
command = "./autogen.sh"

[tasks.configure]
description = "Configure the project."
command = "./configure"

[tasks.build]
description = "Build everything."
command = "make"
args = ["-f", "Makefile", "all"]

[tasks.run]
description = "Run http server."
command = "make"
args = ["-f", "Makefile", "run"]

[tasks.clean]
description = "Clean the project."
command = "make"
args = ["-f", "Makefile", "clean"]
