/*
 * Copyright (C) 2025 ChenPi11
 * This file is part of the chenpi11-blog.
 *
 * chenpi11-blog is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * chenpi11-blog is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with chenpi11-blog.  If not, see <https://www.gnu.org/licenses/>.
 */

"use strict";

export const terminalThemes = {
    // These themes are from Windows Terminal.
    "Campbell": {
        "background": "#0C0C0C",
        "black": "#0C0C0C",
        "blue": "#0037DA",
        "brightBlack": "#767676",
        "brightBlue": "#3B78FF",
        "brightCyan": "#61D6D6",
        "brightGreen": "#16C60C",
        "brightRed": "#E74856",
        "brightWhite": "#F2F2F2",
        "brightYellow": "#F9F1A5",
        "cursorColor": "#FFFFFF",
        "cyan": "#3A96DD",
        "foreground": "#CCCCCC",
        "green": "#13A10E",
        "red": "#C50F1F",
        "selectionBackground": "#FFFFFF",
        "white": "#CCCCCC",
        "yellow": "#C19C00",
        "magenta": "#881798",
        "brightMagenta": "#B4009E"
    },
    "Campbell Powershell": {
        "background": "#012456",
        "black": "#0C0C0C",
        "blue": "#0037DA",
        "brightBlack": "#767676",
        "brightBlue": "#3B78FF",
        "brightCyan": "#61D6D6",
        "brightGreen": "#16C60C",
        "brightRed": "#E74856",
        "brightWhite": "#F2F2F2",
        "brightYellow": "#F9F1A5",
        "cursorColor": "#FFFFFF",
        "cyan": "#3A96DD",
        "foreground": "#CCCCCC",
        "green": "#13A10E",
        "red": "#C50F1F",
        "selectionBackground": "#FFFFFF",
        "white": "#CCCCCC",
        "yellow": "#C19C00",
        "magenta": "#881798",
        "brightMagenta": "#B4009E"
    },
    "One Half Dark": {
        "background": "#282C34",
        "black": "#282C34",
        "blue": "#61AFEF",
        "brightBlack": "#5A6374",
        "brightBlue": "#61AFEF",
        "brightCyan": "#56B6C2",
        "brightGreen": "#98C379",
        "brightRed": "#E06C75",
        "brightWhite": "#DCDFE4",
        "brightYellow": "#E5C07B",
        "cursorColor": "#FFFFFF",
        "cyan": "#56B6C2",
        "foreground": "#DCDFE4",
        "green": "#98C379",
        "red": "#E06C75",
        "selectionBackground": "#FFFFFF",
        "white": "#DCDFE4",
        "yellow": "#E5C07B",
        "magenta": "#C678DD",
        "brightMagenta": "#C678DD"
    },
    "One Half Light": {
        "background": "#FFFFFF",
        "black": "#383A42",
        "blue": "#0184BC",
        "brightBlack": "#4F525D",
        "brightBlue": "#61AFEF",
        "brightCyan": "#56B5C1",
        "brightGreen": "#98C379",
        "brightRed": "#DF6C75",
        "brightWhite": "#FFFFFF",
        "brightYellow": "#E4C07A",
        "cursorColor": "#4F525D",
        "cyan": "#0997B3",
        "foreground": "#383A42",
        "green": "#50A14F",
        "red": "#E45649",
        "selectionBackground": "#FFFFFF",
        "white": "#FAFAFA",
        "yellow": "#C18301",
        "magenta": "#A626A4",
        "brightMagenta": "#C577DD"
    },
    "Vintage": {
        "background": "#FFFFFF",
        "black": "#000000",
        "blue": "#000080",
        "brightBlack": "#808080",
        "brightBlue": "#0000FF",
        "brightCyan": "#00FFFF",
        "brightGreen": "#00FF00",
        "brightRed": "#FF0000",
        "brightWhite": "#FFFFFF",
        "brightYellow": "#FFFF00",
        "cursorColor": "#FFFFFF",
        "cyan": "#008080",
        "foreground": "#C0C0C0",
        "green": "#008000",
        "red": "#800000",
        "selectionBackground": "#FFFFFF",
        "white": "#C0C0C0",
        "yellow": "#808000",
        "magenta": "#800080",
        "brightMagenta": "#FF00FF"
    },
    "Solarized Dark": {
        "background": "#002B36",
        "black": "#002B36",
        "blue": "#268BD2",
        "brightBlack": "#073642",
        "brightBlue": "#839496",
        "brightCyan": "#93A1A1",
        "brightGreen": "#586E75",
        "brightRed": "#CB4B16",
        "brightWhite": "#FDF6E3",
        "brightYellow": "#657B83",
        "cursorColor": "#FFFFFF",
        "cyan": "#2AA198",
        "foreground": "#839496",
        "green": "#859900",
        "red": "#DC322F",
        "selectionBackground": "#FFFFFF",
        "white": "#EEE8D5",
        "yellow": "#B58900",
        "magenta": "#D33682",
        "brightMagenta": "#6C71C4"
    },
    "Solarized Light": {
        "background": "#FDF6E3",
        "black": "#002B36",
        "blue": "#268BD2",
        "brightBlack": "#073642",
        "brightBlue": "#839496",
        "brightCyan": "#93A1A1",
        "brightGreen": "#586E75",
        "brightRed": "#CB4B16",
        "brightWhite": "#FDF6E3",
        "brightYellow": "#657B83",
        "cursorColor": "#002B36",
        "cyan": "#2AA198",
        "foreground": "#657B83",
        "green": "#859900",
        "red": "#DC322F",
        "selectionBackground": "#FFFFFF",
        "white": "#EEE8D5",
        "yellow": "#B58900",
        "magenta": "#D33682",
        "brightMagenta": "#6C71C4"
    },
    "Tango Dark": {
        "background": "#000000",
        "black": "#000000",
        "blue": "#3465A4",
        "brightBlack": "#555753",
        "brightBlue": "#729FCF",
        "brightCyan": "#34E2E2",
        "brightGreen": "#8AE234",
        "brightRed": "#EF2929",
        "brightWhite": "#EEEEEC",
        "brightYellow": "#FCE94F",
        "cursorColor": "#FFFFFF",
        "cyan": "#06989A",
        "foreground": "#D3D7CF",
        "green": "#4E9A06",
        "red": "#CC0000",
        "selectionBackground": "#FFFFFF",
        "white": "#D3D7CF",
        "yellow": "#C4A000",
        "magenta": "#75507B",
        "brightMagenta": "#AD7FA8"
    },
    "Tango Light": {
        "background": "#FFFFFF",
        "black": "#000000",
        "blue": "#3465A4",
        "brightBlack": "#555753",
        "brightBlue": "#729FCF",
        "brightCyan": "#34E2E2",
        "brightGreen": "#8AE234",
        "brightRed": "#EF2929",
        "brightWhite": "#EEEEEC",
        "brightYellow": "#FCE94F",
        "cursorColor": "#000000",
        "cyan": "#06989A",
        "foreground": "#555753",
        "green": "#4E9A06",
        "red": "#CC0000",
        "selectionBackground": "#FFFFFF",
        "white": "#D3D7CF",
        "yellow": "#C4A000",
        "magenta": "#75507B",
        "brightMagenta": "#AD7FA8"
    },
    "Ubuntu": {
        "background": "#300A24",
        "black": "#171421",
        "blue": "#0037DA",
        "brightBlack": "#767676",
        "brightBlue": "#08458F",
        "brightCyan": "#2C9FB3",
        "brightGreen": "#26A269",
        "brightRed": "#C01C28",
        "brightWhite": "#F2F2F2",
        "brightYellow": "#A2734C",
        "cursorColor": "#FFFFFF",
        "cyan": "#3A96DD",
        "foreground": "#FFFFFF",
        "green": "#26A269",
        "red": "#C21A23",
        "selectionBackground": "#FFFFFF",
        "white": "#CCCCCC",
        "yellow": "#A2734C",
        "magenta": "#881798",
        "brightMagenta": "#A347BA"
    },
    // These themes are from Xcolors.
    "Neon": {
        "foreground": "#F8F8F8",
        "background": "#171717",
        "cursor": "#F8F8F8",
        "black": "#171717",
        "brightBlack": "#878787",
        "red": "#D81765",
        "brightRed": "#FF0000",
        "green": "#97D01A",
        "brightGreen": "#76B639",
        "yellow": "#FFA800",
        "brightYellow": "#E1A126",
        "blue": "#16B1FB",
        "brightBlue": "#289CD5",
        "magenta": "#FF2491",
        "brightMagenta": "#FF2491",
        "cyan": "#0FDCB6",
        "brightCyan": "#0A9B81",
        "white": "#EBEBEB",
        "brightWhite": "#F8F8F8"
    }
}

export const defaultTerminalTheme = "Neon";
