#!/bin/sh
# Copyright (C) 2025 ChenPi11.
# This file is part of chenpi11-blog.
#
# chenpi11-blog is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# chenpi11-blog is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with chenpi11-blog.  If not, see <https://www.gnu.org/licenses/>.

# Execute a command in venv.

ROOTDIR=$(dirname "$0")
VENVROOT=$ROOTDIR/.venv
if [ -d "$VENVROOT" ]; then
    # shellcheck source=/dev/null
    . "$VENVROOT/bin/activate"
else
    VENVROOT=$ROOTDIR/../.venv
    if [ -d "$VENVROOT" ]; then
        # shellcheck source=/dev/null
       . "$VENVROOT/bin/activate"
    fi
fi

# shellcheck disable=SC2068
$@
